# Generated by Django 3.1 on 2020-12-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('name',)},
        ),
    ]
